import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Card from "./styles";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  const pokemons = await (
    await fetch("https://pokeapi.co/api/v2/pokemon/?limit=10")
  ).json();

  const data = await Promise.all(
    pokemons.results.map(
      async (pokemon: any) => await (await fetch(pokemon.url)).json()
    )
  );

  // Pass data to the page via props
  return { props: { data } };
}

export default function Home({ data }: any) {
  console.log(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data.map((pokemon: any) => {
          return (
            <Card
              title={pokemon.name}
              imageUrl={pokemon.sprites.front_default}
              description="This is the card description."
            />
          );
        })}
      </div>
    </>
  );
}
